### ISSUE TITLE
`npm start validate` fails after initial clone

### ISSUE THREAD

**Issue by martellaj** [kentcdodds/p-s#78]
- `p-s` version: latest from master
- `node` version: 6.5.0
- `npm` version: 3.10.3

The command executed:

```console
npm start validate
```

The output:

```console
Test Summary
 › Ran all tests matching "src/".
 › 64 tests passed (64 total in 9 test suites, run time 6.792s)
 FAIL  cli-test/cli.test.js
  ✓ without arguments (419ms)
  ✓ with config with default script (416ms)
  ✕ with a missing config (398ms)
  ✓ with --silent (335ms)
  ✓ with --require (1238ms)

  ● with a missing config

    Received value does not match the stored snapshot 1.

    - Snapshot
    + Received

      Object {
    -   "stderr": "Unable to find JS config at "./something-that-does-not-exist.js". Attempted to require as "<projectRootDir>/cli-test/fixtures/something-that-does-not-exist.js" https://github.com/kentcdodds/p-s/blob/v0.0.0-semantically-released/other/ERRORS_AND_WARNINGS.md#unable-to-find-config
    +   "stderr": "Unable to find JS config at "./something-that-does-not-exist.js". Attempted to require as "<projectRootDir>/cli-test/fixtures/something-that-does-not-exist.js" https://github.com/kentcdodds/p-s/blob/v3.0.2/other/ERRORS_AND_WARNINGS.md#unable-to-find-config
      ",
        "stdout": ""
      }

      at cli-test/cli.test.js:34:36
      at run (node_modules/core-js/modules/es6.promise.js:87:22)
      at node_modules/core-js/modules/es6.promise.js:100:28
      at flush (node_modules/core-js/modules/_microtask.js:18:9)


Snapshot Summary
 › 1 snapshot test failed in 1 test file. Inspect your code changes or run with `npm start -- -u` to update them.

Test Summary
 › Ran all tests matching "cli-test/".
 › snapshot failure, 1 test failed, 4 tests passed (5 total in 1 test suite, 4 snapshots, run time 4.895s)
The script called "test.cli" which runs "jest cli-test/" failed with exit code 1 https://github.com/kentcdodds/p-s/blob/v3.0.2/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "build.andValidate" which runs "nps build,test.cli" failed with exit code 1 https://github.com/kentcdodds/p-s/blob/v3.0.2/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
The script called "validate" which runs "nps -p build.andValidate,test,lint" failed with exit code 1 https://github.com/kentcdodds/p-s/blob/v3.0.2/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/martellaj/.nvm/versions/node/v6.5.0/bin/node" "/Users/martellaj/.nvm/versions/node/v6.5.0/bin/npm" "start" "validate"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! p-s@3.0.2 start: `nps "validate"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the p-s@3.0.2 start script 'nps "validate"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the p-s package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nps "validate"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs p-s
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls p-s
npm ERR! There is likely additional logging output above.
```

Problem description:
Interested in digging into the code a bit. Followed instructions in your CONTRIBUTING, but getting failures before I've even opened my IDE.

**Comment by martellaj** [comment]
I'm not familiar with Jest, but it looks like test in question failed... the wrong way.

Received value does not match the stored snapshot 1.

    - Snapshot
    + Received

      Object {
    -   "stderr": "Unable to find JS config at "./something-that-does-not-exist.js". Attempted to require as "<projectRootDir>/cli-test/fixtures/something-that-does-not-exist.js" https://github.com/kentcdodds/p-s/blob/**v0.0.0-semantically-released**/other/ERRORS_AND_WARNINGS.md#unable-to-find-config
    +   "stderr": "Unable to find JS config at "./something-that-does-not-exist.js". Attempted to require as "<projectRootDir>/cli-test/fixtures/something-that-does-not-exist.js" https://github.com/kentcdodds/p-s/blob/**v3.0.2**/other/ERRORS_AND_WARNINGS.md#unable-to-find-config

**Comment by martellaj** [comment]
So really the issue is with the `test.cli` script which `validate` script calls because the bug is in the missing config test in *cli.test.js*. I'd suggest keeping the issue title as is in case anyone else who tries to contribute has a similar issue.

**Comment by kentcdodds** [comment]
Actually, the reason for this bug is I forgot to push a change I have locally to the version in the package.json. it should be `0.0.0-semantically-released`. I'll have that sized soon

**Comment by martellaj** [comment]
If you're interested, I actually went ahead and implemented a different fix such that you can keep your version number in **package.json**. I'll leave it up to you to reject or not. Thanks, Kent!
